{{- if .Values.certificate.mountExternal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-certs
  namespace: {{ .Values.environment.namespace }}
type: Opaque
data:
  {{- range .Values.certificate.files }}
  {{ .name }}: {{ .content }}
  {{- end }}
{{- end }}
